#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

start_service() {
    procd_open_instance "full-vpn"
    procd_set_param command /usr/bin/sing-box run -c /etc/sing-box/config_full_vpn.json
    procd_set_param respawn
    procd_set_param stderr 1
    procd_set_param stdout 1
    procd_close_instance

    procd_open_instance "global-except-ru"
    procd_set_param command /usr/bin/sing-box run -c /etc/sing-box/config_global_except_ru.json
    procd_set_param respawn
    procd_set_param stderr 1
    procd_set_param stdout 1
    procd_close_instance
}
